### ISSUE TITLE
Fails with any storage zone except Falkenstein

### ISSUE THREAD

**Issue by pimterry** [ayeressian/bunnycdn-storage-deploy#20]
This project always uses storage.bunnycdn.com as the API endpoint ([hardcoded here](https://github.com/ayeressian/bunnycdn-storage-deploy/blob/eab2963a0c860d37600b18a08abc53076ac1cf7b/src/uploader.ts#L14)) but in fact, the endpoint varies depending on the storage zone selected (see [Bunny.net docs](https://docs.bunny.net/reference/storage-api#storage-endpoints)). Falkenstein uses storage.bunnycdn.com, but the others vary, e.g. New York uses ny.storage.bunnycdn.com.

If you try to use this action with any storage in a different zone, you get an unexplained unfixable 401 error. Right now, the only solution is to create a new storage zone in Falkenstein instead.

To fix this, it needs to be possible to configure the API endpoint, so you can change that to use the other storage zones.

**Comment by ayeressian** [comment]
@pimterry  fixed in https://github.com/ayeressian/bunnycdn-storage-deploy/pull/22 please use v1.1.0 version.

**Comment by ayeressian** [comment]
Now storageEndpoint can be provided to action.

**Comment by pimterry** [comment]
Amazing, thanks for the quick fix!
