### ISSUE TITLE
Where can I find `pullZoneAccessKey`?

### ISSUE THREAD

**Issue by jansroka** [ayeressian/bunnycdn-storage-deploy#30]
I have trouble locating the right API key, specifically the `pullZoneAccessKey`. Where can I find it on the Bunny Dashboard?

**Comment by ayeressian** [comment]
@jansroka thank you for bringing this up. Apparently, bunny cdn has decided to change its API once again. In the past, each pull zone had its own access key. Apparently, it's not the case anymore and the regular access key should be used. I've fixed it in this PR https://github.com/ayeressian/bunnycdn-storage-deploy/pull/31 . During the testing, I also noticed they changed the file remove behavior. I'll address it in the next PR. Let me know if the purging works as expected for you.
Don't forget to use 1.1.4 version.

**Comment by ayeressian** [comment]
Also removing files has been fixed. Please use 1.1.6.

**Comment by jansroka** [comment]
Thanks, now the action works for me as expected.
