### ISSUE TITLE
Add support for concurrent connections

### ISSUE THREAD

**Issue by jansroka** [ayeressian/bunnycdn-storage-deploy#39]
Thanks for this very useful and nicely working extension.

I use Bunny storage for lots of small files. Uploading those files (thousands of them) takes ages on every deploy. Therefore highest on my wish list would be to implement concurrent connections (= parallel uploading). (The [Bunny API allows up to 75 concurrent connections per zone](https://docs.bunny.net/reference/api-limits)).

Any chance this could be implemented?

**Comment by ayeressian** [comment]
Hi @jansroka, sorry for the late reply, I was very busy recently.
The latest release v2.1.0 supports concurrent upload.
Thank you for bringing this up.

**Comment by jansroka** [comment]
Thanks!
