### ISSUE TITLE
YAML Issue with Alternative Action Runners

### ISSUE THREAD

**Issue by ZicklePop** [ayeressian/bunnycdn-storage-deploy#54]
Hey there, I'm trying to use this with a Gitea Action runner and I'm seeing an error when it tries to run:

```
yaml: unmarshal errors:\n  line 12: cannot unmarshal !!str `false` into bool
```

It's not entirely clear what "line 12" it might be, so forgive me if I'm heading down the wrong road here, but this line in the action.yml looked like it might be related. I know the action uses strings for true and false in some places, but I wonder if this one needs to be an actual boolean?

https://github.com/ayeressian/bunnycdn-storage-deploy/blob/beedf748e5669d7e7edfd936e371f355427e224d/action.yml#L12

**Comment by ayeressian** [comment]
Hi @ZicklePop, Yes it should be boolean according to this https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions#example-specifying-inputs

**Comment by ayeressian** [comment]
will try to fix during this week

**Comment by ayeressian** [comment]
done
